output "name_servers" {
  description = "The Name Servers generated by GCP for this managed zone."
  value       = google_dns_managed_zone.mailgun_dns_zone.name_servers
}

output "zone_id" {
  description = "The ID of the managed zone"
  value       = google_dns_managed_zone.mailgun_dns_zone.id
}