name: 'App CI'

on:
  workflow_call:

jobs:
  validate_source_code:
    name: 'Ruff linter'
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.14'

      - name: Verify Py version
        run: python --version

      - name: Install Linter (Ruff)
        run: pip install ruff

      - name: Run Ruff Linter
        run: ruff check src/ --output-format=github