name: 'Terraform CI'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      WIF_PROVIDER:
        required: true
      CICD_SA:
        required: true
      PROJECT_ID:
        required: true

jobs:
  stateless_checks:
    name: 'TF fmt & validate'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: TF fmt
        run: terraform fmt -check -recursive

      - name: TF validate
        run: |
          for dir in $(find . -type f -name '*.tf' -exec dirname {} \; | sort -u); do
            echo "Validating $dir..."
            cd $dir
            terraform init -backend=false
            terraform validate
            cd -
          done

  tfsec:
    name: 'TFSec Vulnerability Scan'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true
          #working_directory: ./infrastructure/environments/${{ inputs.environment }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  plan:
      name: 'Terraform Plan (${{ inputs.environment }})'
      needs: stateless_checks
      runs-on: self-hosted
      concurrency:
            group: terraform-${{ inputs.environment }}
            cancel-in-progress: false
  
      defaults:
        run:
          working-directory: ./infrastructure/environments/${{ inputs.environment }}
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Authenticate to GCP
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
            service_account: ${{ secrets.CICD_SA }}
  
        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_wrapper: false
  
        - name: Terraform Init
          run: terraform init
  
        - name: Terraform Plan
          run: terraform plan -no-color -out=tfplan

        - name: Convert Plan to Text (PR Comment)
          run: terraform show -no-color tfplan > plan.txt

        - name: Convert Plan to JSON (GCP Vet)
          run: terraform show -json tfplan > tfplan.json

        - name: Clone GCP std policies
          run: git clone https://github.com/GoogleCloudPlatform/policy-library.git

        - name: Enable policies
          run: |
            mkdir -p policy-library/policies/constraints
            cp policy-library/samples/* policy-library/policies/constraints/ 2>/dev/null || true
            
            # Delete Google's broken sample files that crash the validator
            rm -f policy-library/policies/constraints/compute_enable_oslogin_project.yaml
            rm -f policy-library/policies/constraints/gke_enable_binauthz.yaml

        - name: Run gcloud terraform vet
          run: |
            gcloud beta terraform vet tfplan.json \
              --policy-library=policy-library \
              --project=${{ secrets.project_id }} \
              > vet_results.txt 2>&1 || true

        - name: Post Plan and Vet Results to PR
          uses: actions/github-script@v7
          if: github.event_name == 'pull_request'
          env:
            ENV_NAME: ${{ inputs.environment }}
          with:
            script: |
              const fs = require('fs');
              const envName = process.env.ENV_NAME;
              
              const planOutput = fs.readFileSync(`./infrastructure/environments/${envName}/plan.txt`, 'utf8');
              const truncatedPlan = planOutput.length > 60000 
                ? planOutput.substring(0, 60000) + '\n\n... Plan truncated due to GitHub character limits ...' 
                : planOutput;

              let vetOutput = "No vet results generated.";
              try {
                vetOutput = fs.readFileSync(`./infrastructure/environments/${envName}/vet_results.txt`, 'utf8');
              } catch (e) {
                console.log("Vet results file not found, skipping.");
              }

              const commentBody = `### Terraform Execution Plan: \`${envName}\`
              <details><summary><b>Click to view the infrastructure plan</b></summary>
              
              \`\`\`terraform
              ${truncatedPlan}
              \`\`\`
              </details>

              ### GCP Terraform Vet Results
              <details><summary><b>Click to view policy validation results</b></summary>
              
              \`\`\`text
              ${vetOutput}
              \`\`\`
              </details>`;
  
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              })

        - name: Upload TF Plan Artifact
          uses: actions/upload-artifact@v4
          with:
            name: tfplan-${{ inputs.environment }}-artifact
            path: ./infrastructure/environments/${{ inputs.environment }}/tfplan
